name: healix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # State management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  # for dependency injection
  get_it: ^8.0.3
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  pretty_dio_logger: ^1.4.0
  # localization
  intl: ^0.19.0
  # An SVG rendering and widget library for Flutter, which allows painting 
  flutter_svg: ^2.0.17
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.3
  # Flutter library to load and cache network images.
  cached_network_image: ^3.4.1
  # reading and writing simple key-value pairs
  shared_preferences: ^2.5.3
  # provides API to store data in secure storage.
  flutter_secure_storage: ^9.2.4
  # easy way to add shimmer effect
  skeletonizer: ^1.4.3
  # Functional Programming in Dart.
  dartz: ^0.10.1
  #Render After Effects animations natively
  lottie: ^3.3.1
  # snackbar experience with various alert messages i.e. success, failure, help or warning 
  awesome_snackbar_content: ^0.1.5
  # Google fonts
  google_fonts: ^6.2.0
  # Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.2.1
  # pin code input
  pin_code_fields: ^8.0.1
  # Maps and location picker
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  google_maps_flutter: ^2.12.1
  # Carousel slider
  carousel_slider_plus: ^7.1.0
  # Easily configure global variables using a `.env` file.
  flutter_dotenv: ^5.2.1
  # File picker
  file_picker: ^10.1.2
  # Customize Flutter's default white native splash screen with background color and splash image
  flutter_native_splash: ^2.4.4

dev_dependencies:
  #A build system for Dart code generation and modular compilation
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/svgs/
    - assets/lotties/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic


flutter_gen:
  output: lib/core/gen/ 
  line_length: 80 

  # Optional
  integrations:
    flutter_svg: true
    rive: true
    lottie: true  